name: Rubocup checking
on: [push,pull_request]
jobs:
  test:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: Install Rubocop
        run: gem install rubocop
      - name: Check code
        run: rubocop